name: flying_fish
description: The full stack Dart framework you've been waiting for. Flying Fish projects have an API layer, and a Flutter layer that enables you to write full stack applications in Dart.
version: 0.0.4
# homepage: https://www.example.com
repository: https://github.com/flutter-fish/flying_fish

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  args: ^2.3.1
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
